config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # devise_for :users
  root to: "posts#index"
  resources :admins
  resources :posts  
end

app/models/admin.rb
class Admin < ApplicationRecord
	has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :admin ,optional: true
	validates :title, presence: true, length: {maximum: 140}
	validates :body, presence: true
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
# before_action :authenticate_user!
  before_action :find_post, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]

  # Index action to render all posts
  def index       
    @posts = Post.all        
  end
  # New action for creating post
  def new
    @post = Post.new()     
  end
  # Create action saves the post into database
  def create
    @post = current_admin.posts.new(post_params)
    if @post.save!
      redirect_to @post
    else
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
    @post = Post.find(params[:id])
  end

  # Update action updates the post with the new information
  def update
    if @post.update(post_params)
      flash[:notice] = "Successfully updated post!"
      redirect_to post_path
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
    @post = Post.find(params[:id])
  end

  # The destroy action removes the post permanently from the database
  def destroy  
    if @post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error updating post!"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<div class="col-sm-offset-4 col-sm-4 col-xs-12">
  <% if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.omniauthable? %>
    <% resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">My Blogs</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <% if admin_signed_in? %>
        <!--This block is only visible to signed in admins -->
          <li><%= link_to 'New Post', new_post_path %></li>
          <!-- <li><%= link_to 'My Account', edit_admin_registration_path  %></li> -->
          <li><%= link_to 'Logout', destroy_admin_session_path, :method => :delete %></li>
        <!-- The block ends here -->
        <% else %>
          <li><%= link_to 'Login', new_admin_session_path  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render "layouts/navigation" %>
    
    <%= yield %>
    <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/posts/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Article 
  </title>
</head>
<body>
  <center>
    <h2 style="color: pink">
      Create new post
    </h2>
<%= form_with model: post do |form| %>
  <div  class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title %>     
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>      
  </div>
  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>
</center>
</body>
</html>

app/views/posts/edit.html.erb
<h2>Edit post</h2>
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<style>
		table, th, td 
		 {
		  border: 1px solid #ddd;
		  padding: 8px;
		}

		.center {
		  margin-left: auto;
		  margin-right: auto;
		}

		th {
		  padding-top: 12px;
		  padding-bottom: 12px;
		  text-align: left;
		  background-color: #4CAF50;
		  color: white;
		}
	</style>
	<title>
		index page
	</title>
</head>
<body>
	<div style="background-color: pink; color: black; text-shadow: 2px; height: 200px;width: 100%">
		<h3 style="margin-left: 25px;margin-top: 15px">
			Welcome To MyBlogs
		</h3>			
	</div>
	<% if admin_signed_in? %>
	<h2 class="text-center">
		Your Posts
	</h2>
		<table class="center">
			<tr>
			<th>
				Title
			</th>			
			<th>
				Body
			</th>
			<th>
				Actions
			</th>
			<th>
				Image
			</th>
		</tr>	
		<% Post.all.each do |post| %>  
			<tr>
				<td>
					<%= post.title%>
				</td>
				<td>
					<%= post.body%>
				</td>
				<td>
					<%= link_to "Edit", edit_post_path(post), class: "btn btn-default" %>
					
					<%= link_to "Delete",post_path(post), class: "btn btn-danger", data: {:confirm => "Are you sure?"}, :method => :delete %>
 				</td>	
 				<td>
 					<%= image_tag(post.image.url,size: "40x40", alt: 'Image') if post.image? %>
 				</td>
			</tr> 
		<% end %>		
		</table>
	<% end %>
</body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>
		new page
	</title>
</head>
<body>
<%= render "form", post: @post %>
</body>
</html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style>
		table, th, td 
		 {
		  border: 1px solid #ddd;
		  padding: 8px;
		}

		.center {
		  margin-left: auto;
		  margin-right: auto;
		}

		th {
		  padding-top: 12px;
		  padding-bottom: 12px;
		  text-align: left;
		  background-color: #4CAF50;
		  color: white;
		}

	</style>
</head>
<body>
	<h2 class="text-center">
		Articles
	</h2>
<div>
	<table class="center">
		<tr>
		<th>
			Title
		</th>			
		<th>
			Body
		</th>
		<th>
			Images
		</th>

		<th>
			Actions
		</th>
	</tr>		 
	<tr>
		<td>
			<%= @post.title%>
		</td>
		<td>
			<%= @post.body%>
		</td>
		<td>
			<%= image_tag(@post.image.url, size: "30x30",alt: 'Image') if @post.image? %>
		</td>
		<td>
			<%= link_to "Edit", edit_post_path, class: "btn btn-default" %>
			
			<%= button_to "Delete",post_path(@post), data: {:confirm => "Are you sure?"}, :method => :delete, controller: :posts %>
 		</td>		
	</tr> 	
	</table>    
</div>
</body>
</html>